package cn.zzfyip.search.dal.common.vo;

import java.util.Date;

public class PatentStatisticVo {
	private String extInfo;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.patent_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String patentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.apply_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private Date applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.patent_name
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String patentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.public_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String publicNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.public_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private Date publicDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.main_category_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String mainCategoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.pre_apply_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String preApplyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.sec_category_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String secCategoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.certificate_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private Date certificateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.pre_right
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String preRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.applier
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String applier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.address
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.inventor
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String inventor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.global_patent
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String globalPatent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.global_public
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String globalPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.entry_country_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private Date entryCountryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.agency
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String agency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.agent
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String agent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.summary
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_info.add_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    private Date addDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.patent_no
     *
     * @return the value of public.patent_info.patent_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getPatentNo() {
        return patentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.patent_no
     *
     * @param patentNo the value for public.patent_info.patent_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setPatentNo(String patentNo) {
        this.patentNo = patentNo == null ? null : patentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.apply_date
     *
     * @return the value of public.patent_info.apply_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.apply_date
     *
     * @param applyDate the value for public.patent_info.apply_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.patent_name
     *
     * @return the value of public.patent_info.patent_name
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getPatentName() {
        return patentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.patent_name
     *
     * @param patentName the value for public.patent_info.patent_name
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setPatentName(String patentName) {
        this.patentName = patentName == null ? null : patentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.public_no
     *
     * @return the value of public.patent_info.public_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getPublicNo() {
        return publicNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.public_no
     *
     * @param publicNo the value for public.patent_info.public_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setPublicNo(String publicNo) {
        this.publicNo = publicNo == null ? null : publicNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.public_date
     *
     * @return the value of public.patent_info.public_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public Date getPublicDate() {
        return publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.public_date
     *
     * @param publicDate the value for public.patent_info.public_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setPublicDate(Date publicDate) {
        this.publicDate = publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.main_category_no
     *
     * @return the value of public.patent_info.main_category_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getMainCategoryNo() {
        return mainCategoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.main_category_no
     *
     * @param mainCategoryNo the value for public.patent_info.main_category_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setMainCategoryNo(String mainCategoryNo) {
        this.mainCategoryNo = mainCategoryNo == null ? null : mainCategoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.pre_apply_no
     *
     * @return the value of public.patent_info.pre_apply_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getPreApplyNo() {
        return preApplyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.pre_apply_no
     *
     * @param preApplyNo the value for public.patent_info.pre_apply_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setPreApplyNo(String preApplyNo) {
        this.preApplyNo = preApplyNo == null ? null : preApplyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.sec_category_no
     *
     * @return the value of public.patent_info.sec_category_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getSecCategoryNo() {
        return secCategoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.sec_category_no
     *
     * @param secCategoryNo the value for public.patent_info.sec_category_no
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setSecCategoryNo(String secCategoryNo) {
        this.secCategoryNo = secCategoryNo == null ? null : secCategoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.certificate_date
     *
     * @return the value of public.patent_info.certificate_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public Date getCertificateDate() {
        return certificateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.certificate_date
     *
     * @param certificateDate the value for public.patent_info.certificate_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setCertificateDate(Date certificateDate) {
        this.certificateDate = certificateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.pre_right
     *
     * @return the value of public.patent_info.pre_right
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getPreRight() {
        return preRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.pre_right
     *
     * @param preRight the value for public.patent_info.pre_right
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setPreRight(String preRight) {
        this.preRight = preRight == null ? null : preRight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.applier
     *
     * @return the value of public.patent_info.applier
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getApplier() {
        return applier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.applier
     *
     * @param applier the value for public.patent_info.applier
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setApplier(String applier) {
        this.applier = applier == null ? null : applier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.address
     *
     * @return the value of public.patent_info.address
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.address
     *
     * @param address the value for public.patent_info.address
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.inventor
     *
     * @return the value of public.patent_info.inventor
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getInventor() {
        return inventor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.inventor
     *
     * @param inventor the value for public.patent_info.inventor
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setInventor(String inventor) {
        this.inventor = inventor == null ? null : inventor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.global_patent
     *
     * @return the value of public.patent_info.global_patent
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getGlobalPatent() {
        return globalPatent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.global_patent
     *
     * @param globalPatent the value for public.patent_info.global_patent
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setGlobalPatent(String globalPatent) {
        this.globalPatent = globalPatent == null ? null : globalPatent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.global_public
     *
     * @return the value of public.patent_info.global_public
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getGlobalPublic() {
        return globalPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.global_public
     *
     * @param globalPublic the value for public.patent_info.global_public
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setGlobalPublic(String globalPublic) {
        this.globalPublic = globalPublic == null ? null : globalPublic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.entry_country_date
     *
     * @return the value of public.patent_info.entry_country_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public Date getEntryCountryDate() {
        return entryCountryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.entry_country_date
     *
     * @param entryCountryDate the value for public.patent_info.entry_country_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setEntryCountryDate(Date entryCountryDate) {
        this.entryCountryDate = entryCountryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.agency
     *
     * @return the value of public.patent_info.agency
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getAgency() {
        return agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.agency
     *
     * @param agency the value for public.patent_info.agency
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setAgency(String agency) {
        this.agency = agency == null ? null : agency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.agent
     *
     * @return the value of public.patent_info.agent
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.agent
     *
     * @param agent the value for public.patent_info.agent
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setAgent(String agent) {
        this.agent = agent == null ? null : agent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.summary
     *
     * @return the value of public.patent_info.summary
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.summary
     *
     * @param summary the value for public.patent_info.summary
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_info.add_date
     *
     * @return the value of public.patent_info.add_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_info.add_date
     *
     * @param addDate the value for public.patent_info.add_date
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

	public String getExtInfo() {
		return extInfo;
	}

	public void setExtInfo(String extInfo) {
		this.extInfo = extInfo;
	}

}
