package cn.zzfyip.search.dal.common.mapper;

import cn.zzfyip.search.common.annotation.Mapper;
import cn.zzfyip.search.dal.common.entity.AddPatentRecord;
import cn.zzfyip.search.dal.common.entity.AddPatentRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AddPatentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.add_patent_record
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    int countByExample(AddPatentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.add_patent_record
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    int deleteByExample(AddPatentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.add_patent_record
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.add_patent_record
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    int insert(AddPatentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.add_patent_record
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    int insertSelective(AddPatentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.add_patent_record
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    List<AddPatentRecord> selectByExample(AddPatentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.add_patent_record
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    AddPatentRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.add_patent_record
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    int updateByExampleSelective(@Param("record") AddPatentRecord record, @Param("example") AddPatentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.add_patent_record
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    int updateByExample(@Param("record") AddPatentRecord record, @Param("example") AddPatentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.add_patent_record
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    int updateByPrimaryKeySelective(AddPatentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.add_patent_record
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    int updateByPrimaryKey(AddPatentRecord record);
}