package cn.zzfyip.search.dal.common.mapper;

import cn.zzfyip.search.common.annotation.Mapper;
import cn.zzfyip.search.dal.common.entity.PatentInfo;
import cn.zzfyip.search.dal.common.entity.PatentInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PatentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int countByExample(PatentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int deleteByExample(PatentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int deleteByPrimaryKey(String patentNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int insert(PatentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int insertSelective(PatentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    List<PatentInfo> selectByExample(PatentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    PatentInfo selectByPrimaryKey(String patentNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByExampleSelective(@Param("record") PatentInfo record, @Param("example") PatentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByExample(@Param("record") PatentInfo record, @Param("example") PatentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByPrimaryKeySelective(PatentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByPrimaryKey(PatentInfo record);
}