package cn.zzfyip.search.dal.common.mapper;

import cn.zzfyip.search.common.annotation.Mapper;
import cn.zzfyip.search.dal.common.entity.PatentFee;
import cn.zzfyip.search.dal.common.entity.PatentFeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PatentFeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_fee
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int countByExample(PatentFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_fee
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int deleteByExample(PatentFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_fee
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int deleteByPrimaryKey(String patentNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_fee
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int insert(PatentFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_fee
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int insertSelective(PatentFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_fee
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    List<PatentFee> selectByExample(PatentFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_fee
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    PatentFee selectByPrimaryKey(String patentNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_fee
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByExampleSelective(@Param("record") PatentFee record, @Param("example") PatentFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_fee
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByExample(@Param("record") PatentFee record, @Param("example") PatentFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_fee
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByPrimaryKeySelective(PatentFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_fee
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByPrimaryKey(PatentFee record);
}