package cn.zzfyip.search.dal.common.mapper;

import cn.zzfyip.search.common.annotation.Mapper;
import cn.zzfyip.search.dal.common.entity.PatentNoticeFawen;
import cn.zzfyip.search.dal.common.entity.PatentNoticeFawenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PatentNoticeFawenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_notice_fawen
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int countByExample(PatentNoticeFawenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_notice_fawen
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int deleteByExample(PatentNoticeFawenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_notice_fawen
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int deleteByPrimaryKey(String patentNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_notice_fawen
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int insert(PatentNoticeFawen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_notice_fawen
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int insertSelective(PatentNoticeFawen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_notice_fawen
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    List<PatentNoticeFawen> selectByExample(PatentNoticeFawenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_notice_fawen
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    PatentNoticeFawen selectByPrimaryKey(String patentNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_notice_fawen
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByExampleSelective(@Param("record") PatentNoticeFawen record, @Param("example") PatentNoticeFawenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_notice_fawen
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByExample(@Param("record") PatentNoticeFawen record, @Param("example") PatentNoticeFawenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_notice_fawen
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByPrimaryKeySelective(PatentNoticeFawen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_notice_fawen
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    int updateByPrimaryKey(PatentNoticeFawen record);
}