package cn.zzfyip.search.dal.common.mapper;

import cn.zzfyip.search.common.annotation.Mapper;
import cn.zzfyip.search.dal.common.entity.PatentStatisticJob;
import cn.zzfyip.search.dal.common.entity.PatentStatisticJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PatentStatisticJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_statistic_job
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    int countByExample(PatentStatisticJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_statistic_job
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    int deleteByExample(PatentStatisticJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_statistic_job
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_statistic_job
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    int insert(PatentStatisticJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_statistic_job
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    int insertSelective(PatentStatisticJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_statistic_job
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    List<PatentStatisticJob> selectByExample(PatentStatisticJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_statistic_job
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    PatentStatisticJob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_statistic_job
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    int updateByExampleSelective(@Param("record") PatentStatisticJob record, @Param("example") PatentStatisticJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_statistic_job
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    int updateByExample(@Param("record") PatentStatisticJob record, @Param("example") PatentStatisticJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_statistic_job
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    int updateByPrimaryKeySelective(PatentStatisticJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_statistic_job
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    int updateByPrimaryKey(PatentStatisticJob record);
}