package cn.zzfyip.search.dal.common.entity;

import java.util.Date;

public class AddPatentRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.add_patent_record.id
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.add_patent_record.public_date
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    private Date publicDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.add_patent_record.patent_type
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    private Short patentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.add_patent_record.total_page
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    private Long totalPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.add_patent_record.per_page_num
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    private Long perPageNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.add_patent_record.current_page
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    private Long currentPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.add_patent_record.load_status
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    private Short loadStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.add_patent_record.add_date
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    private Date addDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.add_patent_record.id
     *
     * @return the value of public.add_patent_record.id
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.add_patent_record.id
     *
     * @param id the value for public.add_patent_record.id
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.add_patent_record.public_date
     *
     * @return the value of public.add_patent_record.public_date
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public Date getPublicDate() {
        return publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.add_patent_record.public_date
     *
     * @param publicDate the value for public.add_patent_record.public_date
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public void setPublicDate(Date publicDate) {
        this.publicDate = publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.add_patent_record.patent_type
     *
     * @return the value of public.add_patent_record.patent_type
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public Short getPatentType() {
        return patentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.add_patent_record.patent_type
     *
     * @param patentType the value for public.add_patent_record.patent_type
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public void setPatentType(Short patentType) {
        this.patentType = patentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.add_patent_record.total_page
     *
     * @return the value of public.add_patent_record.total_page
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public Long getTotalPage() {
        return totalPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.add_patent_record.total_page
     *
     * @param totalPage the value for public.add_patent_record.total_page
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public void setTotalPage(Long totalPage) {
        this.totalPage = totalPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.add_patent_record.per_page_num
     *
     * @return the value of public.add_patent_record.per_page_num
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public Long getPerPageNum() {
        return perPageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.add_patent_record.per_page_num
     *
     * @param perPageNum the value for public.add_patent_record.per_page_num
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public void setPerPageNum(Long perPageNum) {
        this.perPageNum = perPageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.add_patent_record.current_page
     *
     * @return the value of public.add_patent_record.current_page
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public Long getCurrentPage() {
        return currentPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.add_patent_record.current_page
     *
     * @param currentPage the value for public.add_patent_record.current_page
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public void setCurrentPage(Long currentPage) {
        this.currentPage = currentPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.add_patent_record.load_status
     *
     * @return the value of public.add_patent_record.load_status
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public Short getLoadStatus() {
        return loadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.add_patent_record.load_status
     *
     * @param loadStatus the value for public.add_patent_record.load_status
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public void setLoadStatus(Short loadStatus) {
        this.loadStatus = loadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.add_patent_record.add_date
     *
     * @return the value of public.add_patent_record.add_date
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.add_patent_record.add_date
     *
     * @param addDate the value for public.add_patent_record.add_date
     *
     * @mbggenerated Fri Dec 27 15:52:41 CST 2013
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
}