package cn.zzfyip.search.dal.common.entity;

import java.util.Date;

public class PatentMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_main.patent_no
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    private String patentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_main.patent_name
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    private String patentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_main.public_date
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    private Date publicDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_main.patent_status
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    private String patentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_main.add_date
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    private Date addDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_main.patent_type
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    private Short patentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_main.patent_fawen_search_type
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    private String patentFawenSearchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_main.patent_fawen_search_time
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    private Date patentFawenSearchTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_main.patent_no
     *
     * @return the value of public.patent_main.patent_no
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public String getPatentNo() {
        return patentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_main.patent_no
     *
     * @param patentNo the value for public.patent_main.patent_no
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public void setPatentNo(String patentNo) {
        this.patentNo = patentNo == null ? null : patentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_main.patent_name
     *
     * @return the value of public.patent_main.patent_name
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public String getPatentName() {
        return patentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_main.patent_name
     *
     * @param patentName the value for public.patent_main.patent_name
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public void setPatentName(String patentName) {
        this.patentName = patentName == null ? null : patentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_main.public_date
     *
     * @return the value of public.patent_main.public_date
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public Date getPublicDate() {
        return publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_main.public_date
     *
     * @param publicDate the value for public.patent_main.public_date
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public void setPublicDate(Date publicDate) {
        this.publicDate = publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_main.patent_status
     *
     * @return the value of public.patent_main.patent_status
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public String getPatentStatus() {
        return patentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_main.patent_status
     *
     * @param patentStatus the value for public.patent_main.patent_status
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public void setPatentStatus(String patentStatus) {
        this.patentStatus = patentStatus == null ? null : patentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_main.add_date
     *
     * @return the value of public.patent_main.add_date
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_main.add_date
     *
     * @param addDate the value for public.patent_main.add_date
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_main.patent_type
     *
     * @return the value of public.patent_main.patent_type
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public Short getPatentType() {
        return patentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_main.patent_type
     *
     * @param patentType the value for public.patent_main.patent_type
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public void setPatentType(Short patentType) {
        this.patentType = patentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_main.patent_fawen_search_type
     *
     * @return the value of public.patent_main.patent_fawen_search_type
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public String getPatentFawenSearchType() {
        return patentFawenSearchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_main.patent_fawen_search_type
     *
     * @param patentFawenSearchType the value for public.patent_main.patent_fawen_search_type
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public void setPatentFawenSearchType(String patentFawenSearchType) {
        this.patentFawenSearchType = patentFawenSearchType == null ? null : patentFawenSearchType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_main.patent_fawen_search_time
     *
     * @return the value of public.patent_main.patent_fawen_search_time
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public Date getPatentFawenSearchTime() {
        return patentFawenSearchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_main.patent_fawen_search_time
     *
     * @param patentFawenSearchTime the value for public.patent_main.patent_fawen_search_time
     *
     * @mbggenerated Thu Jan 09 06:17:14 CST 2014
     */
    public void setPatentFawenSearchTime(Date patentFawenSearchTime) {
        this.patentFawenSearchTime = patentFawenSearchTime;
    }
}