package cn.zzfyip.search.dal.common.entity;

import java.util.Date;

public class PatentStatisticJob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_statistic_job.id
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_statistic_job.job_type
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    private String jobType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_statistic_job.fawen_update_date
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    private Date fawenUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_statistic_job.job_status
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    private String jobStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_statistic_job.id
     *
     * @return the value of public.patent_statistic_job.id
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_statistic_job.id
     *
     * @param id the value for public.patent_statistic_job.id
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_statistic_job.job_type
     *
     * @return the value of public.patent_statistic_job.job_type
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    public String getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_statistic_job.job_type
     *
     * @param jobType the value for public.patent_statistic_job.job_type
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    public void setJobType(String jobType) {
        this.jobType = jobType == null ? null : jobType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_statistic_job.fawen_update_date
     *
     * @return the value of public.patent_statistic_job.fawen_update_date
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    public Date getFawenUpdateDate() {
        return fawenUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_statistic_job.fawen_update_date
     *
     * @param fawenUpdateDate the value for public.patent_statistic_job.fawen_update_date
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    public void setFawenUpdateDate(Date fawenUpdateDate) {
        this.fawenUpdateDate = fawenUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_statistic_job.job_status
     *
     * @return the value of public.patent_statistic_job.job_status
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    public String getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_statistic_job.job_status
     *
     * @param jobStatus the value for public.patent_statistic_job.job_status
     *
     * @mbggenerated Sat Feb 08 09:58:45 CST 2014
     */
    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus == null ? null : jobStatus.trim();
    }
}