package cn.zzfyip.search.dal.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatentMainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    public PatentMainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPatentNoIsNull() {
            addCriterion("patent_no is null");
            return (Criteria) this;
        }

        public Criteria andPatentNoIsNotNull() {
            addCriterion("patent_no is not null");
            return (Criteria) this;
        }

        public Criteria andPatentNoEqualTo(String value) {
            addCriterion("patent_no =", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoNotEqualTo(String value) {
            addCriterion("patent_no <>", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoGreaterThan(String value) {
            addCriterion("patent_no >", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoGreaterThanOrEqualTo(String value) {
            addCriterion("patent_no >=", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoLessThan(String value) {
            addCriterion("patent_no <", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoLessThanOrEqualTo(String value) {
            addCriterion("patent_no <=", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoLike(String value) {
            addCriterion("patent_no like", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoNotLike(String value) {
            addCriterion("patent_no not like", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoIn(List<String> values) {
            addCriterion("patent_no in", values, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoNotIn(List<String> values) {
            addCriterion("patent_no not in", values, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoBetween(String value1, String value2) {
            addCriterion("patent_no between", value1, value2, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoNotBetween(String value1, String value2) {
            addCriterion("patent_no not between", value1, value2, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNameIsNull() {
            addCriterion("patent_name is null");
            return (Criteria) this;
        }

        public Criteria andPatentNameIsNotNull() {
            addCriterion("patent_name is not null");
            return (Criteria) this;
        }

        public Criteria andPatentNameEqualTo(String value) {
            addCriterion("patent_name =", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameNotEqualTo(String value) {
            addCriterion("patent_name <>", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameGreaterThan(String value) {
            addCriterion("patent_name >", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameGreaterThanOrEqualTo(String value) {
            addCriterion("patent_name >=", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameLessThan(String value) {
            addCriterion("patent_name <", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameLessThanOrEqualTo(String value) {
            addCriterion("patent_name <=", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameLike(String value) {
            addCriterion("patent_name like", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameNotLike(String value) {
            addCriterion("patent_name not like", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameIn(List<String> values) {
            addCriterion("patent_name in", values, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameNotIn(List<String> values) {
            addCriterion("patent_name not in", values, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameBetween(String value1, String value2) {
            addCriterion("patent_name between", value1, value2, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameNotBetween(String value1, String value2) {
            addCriterion("patent_name not between", value1, value2, "patentName");
            return (Criteria) this;
        }

        public Criteria andPublicDateIsNull() {
            addCriterion("public_date is null");
            return (Criteria) this;
        }

        public Criteria andPublicDateIsNotNull() {
            addCriterion("public_date is not null");
            return (Criteria) this;
        }

        public Criteria andPublicDateEqualTo(Date value) {
            addCriterion("public_date =", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateNotEqualTo(Date value) {
            addCriterion("public_date <>", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateGreaterThan(Date value) {
            addCriterion("public_date >", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateGreaterThanOrEqualTo(Date value) {
            addCriterion("public_date >=", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateLessThan(Date value) {
            addCriterion("public_date <", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateLessThanOrEqualTo(Date value) {
            addCriterion("public_date <=", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateIn(List<Date> values) {
            addCriterion("public_date in", values, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateNotIn(List<Date> values) {
            addCriterion("public_date not in", values, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateBetween(Date value1, Date value2) {
            addCriterion("public_date between", value1, value2, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateNotBetween(Date value1, Date value2) {
            addCriterion("public_date not between", value1, value2, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPatentStatusIsNull() {
            addCriterion("patent_status is null");
            return (Criteria) this;
        }

        public Criteria andPatentStatusIsNotNull() {
            addCriterion("patent_status is not null");
            return (Criteria) this;
        }

        public Criteria andPatentStatusEqualTo(String value) {
            addCriterion("patent_status =", value, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andPatentStatusNotEqualTo(String value) {
            addCriterion("patent_status <>", value, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andPatentStatusGreaterThan(String value) {
            addCriterion("patent_status >", value, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andPatentStatusGreaterThanOrEqualTo(String value) {
            addCriterion("patent_status >=", value, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andPatentStatusLessThan(String value) {
            addCriterion("patent_status <", value, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andPatentStatusLessThanOrEqualTo(String value) {
            addCriterion("patent_status <=", value, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andPatentStatusLike(String value) {
            addCriterion("patent_status like", value, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andPatentStatusNotLike(String value) {
            addCriterion("patent_status not like", value, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andPatentStatusIn(List<String> values) {
            addCriterion("patent_status in", values, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andPatentStatusNotIn(List<String> values) {
            addCriterion("patent_status not in", values, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andPatentStatusBetween(String value1, String value2) {
            addCriterion("patent_status between", value1, value2, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andPatentStatusNotBetween(String value1, String value2) {
            addCriterion("patent_status not between", value1, value2, "patentStatus");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNull() {
            addCriterion("add_date is null");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNotNull() {
            addCriterion("add_date is not null");
            return (Criteria) this;
        }

        public Criteria andAddDateEqualTo(Date value) {
            addCriterion("add_date =", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotEqualTo(Date value) {
            addCriterion("add_date <>", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThan(Date value) {
            addCriterion("add_date >", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThanOrEqualTo(Date value) {
            addCriterion("add_date >=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThan(Date value) {
            addCriterion("add_date <", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThanOrEqualTo(Date value) {
            addCriterion("add_date <=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateIn(List<Date> values) {
            addCriterion("add_date in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotIn(List<Date> values) {
            addCriterion("add_date not in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateBetween(Date value1, Date value2) {
            addCriterion("add_date between", value1, value2, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotBetween(Date value1, Date value2) {
            addCriterion("add_date not between", value1, value2, "addDate");
            return (Criteria) this;
        }

        public Criteria andPatentTypeIsNull() {
            addCriterion("patent_type is null");
            return (Criteria) this;
        }

        public Criteria andPatentTypeIsNotNull() {
            addCriterion("patent_type is not null");
            return (Criteria) this;
        }

        public Criteria andPatentTypeEqualTo(Short value) {
            addCriterion("patent_type =", value, "patentType");
            return (Criteria) this;
        }

        public Criteria andPatentTypeNotEqualTo(Short value) {
            addCriterion("patent_type <>", value, "patentType");
            return (Criteria) this;
        }

        public Criteria andPatentTypeGreaterThan(Short value) {
            addCriterion("patent_type >", value, "patentType");
            return (Criteria) this;
        }

        public Criteria andPatentTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("patent_type >=", value, "patentType");
            return (Criteria) this;
        }

        public Criteria andPatentTypeLessThan(Short value) {
            addCriterion("patent_type <", value, "patentType");
            return (Criteria) this;
        }

        public Criteria andPatentTypeLessThanOrEqualTo(Short value) {
            addCriterion("patent_type <=", value, "patentType");
            return (Criteria) this;
        }

        public Criteria andPatentTypeIn(List<Short> values) {
            addCriterion("patent_type in", values, "patentType");
            return (Criteria) this;
        }

        public Criteria andPatentTypeNotIn(List<Short> values) {
            addCriterion("patent_type not in", values, "patentType");
            return (Criteria) this;
        }

        public Criteria andPatentTypeBetween(Short value1, Short value2) {
            addCriterion("patent_type between", value1, value2, "patentType");
            return (Criteria) this;
        }

        public Criteria andPatentTypeNotBetween(Short value1, Short value2) {
            addCriterion("patent_type not between", value1, value2, "patentType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeIsNull() {
            addCriterion("patent_fawen_search_type is null");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeIsNotNull() {
            addCriterion("patent_fawen_search_type is not null");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeEqualTo(String value) {
            addCriterion("patent_fawen_search_type =", value, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeNotEqualTo(String value) {
            addCriterion("patent_fawen_search_type <>", value, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeGreaterThan(String value) {
            addCriterion("patent_fawen_search_type >", value, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeGreaterThanOrEqualTo(String value) {
            addCriterion("patent_fawen_search_type >=", value, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeLessThan(String value) {
            addCriterion("patent_fawen_search_type <", value, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeLessThanOrEqualTo(String value) {
            addCriterion("patent_fawen_search_type <=", value, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeLike(String value) {
            addCriterion("patent_fawen_search_type like", value, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeNotLike(String value) {
            addCriterion("patent_fawen_search_type not like", value, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeIn(List<String> values) {
            addCriterion("patent_fawen_search_type in", values, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeNotIn(List<String> values) {
            addCriterion("patent_fawen_search_type not in", values, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeBetween(String value1, String value2) {
            addCriterion("patent_fawen_search_type between", value1, value2, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTypeNotBetween(String value1, String value2) {
            addCriterion("patent_fawen_search_type not between", value1, value2, "patentFawenSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeIsNull() {
            addCriterion("patent_fawen_search_time is null");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeIsNotNull() {
            addCriterion("patent_fawen_search_time is not null");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeEqualTo(Date value) {
            addCriterion("patent_fawen_search_time =", value, "patentFawenSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeNotEqualTo(Date value) {
            addCriterion("patent_fawen_search_time <>", value, "patentFawenSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeGreaterThan(Date value) {
            addCriterion("patent_fawen_search_time >", value, "patentFawenSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("patent_fawen_search_time >=", value, "patentFawenSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeLessThan(Date value) {
            addCriterion("patent_fawen_search_time <", value, "patentFawenSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeLessThanOrEqualTo(Date value) {
            addCriterion("patent_fawen_search_time <=", value, "patentFawenSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeIn(List<Date> values) {
            addCriterion("patent_fawen_search_time in", values, "patentFawenSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeNotIn(List<Date> values) {
            addCriterion("patent_fawen_search_time not in", values, "patentFawenSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeBetween(Date value1, Date value2) {
            addCriterion("patent_fawen_search_time between", value1, value2, "patentFawenSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFawenSearchTimeNotBetween(Date value1, Date value2) {
            addCriterion("patent_fawen_search_time not between", value1, value2, "patentFawenSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesIsNull() {
            addCriterion("patent_fawen_error_times is null");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesIsNotNull() {
            addCriterion("patent_fawen_error_times is not null");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesEqualTo(Integer value) {
            addCriterion("patent_fawen_error_times =", value, "patentFawenErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesNotEqualTo(Integer value) {
            addCriterion("patent_fawen_error_times <>", value, "patentFawenErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesGreaterThan(Integer value) {
            addCriterion("patent_fawen_error_times >", value, "patentFawenErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("patent_fawen_error_times >=", value, "patentFawenErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesLessThan(Integer value) {
            addCriterion("patent_fawen_error_times <", value, "patentFawenErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesLessThanOrEqualTo(Integer value) {
            addCriterion("patent_fawen_error_times <=", value, "patentFawenErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesIn(List<Integer> values) {
            addCriterion("patent_fawen_error_times in", values, "patentFawenErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesNotIn(List<Integer> values) {
            addCriterion("patent_fawen_error_times not in", values, "patentFawenErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesBetween(Integer value1, Integer value2) {
            addCriterion("patent_fawen_error_times between", value1, value2, "patentFawenErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentFawenErrorTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("patent_fawen_error_times not between", value1, value2, "patentFawenErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesIsNull() {
            addCriterion("patent_info_error_times is null");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesIsNotNull() {
            addCriterion("patent_info_error_times is not null");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesEqualTo(Integer value) {
            addCriterion("patent_info_error_times =", value, "patentInfoErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesNotEqualTo(Integer value) {
            addCriterion("patent_info_error_times <>", value, "patentInfoErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesGreaterThan(Integer value) {
            addCriterion("patent_info_error_times >", value, "patentInfoErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("patent_info_error_times >=", value, "patentInfoErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesLessThan(Integer value) {
            addCriterion("patent_info_error_times <", value, "patentInfoErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesLessThanOrEqualTo(Integer value) {
            addCriterion("patent_info_error_times <=", value, "patentInfoErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesIn(List<Integer> values) {
            addCriterion("patent_info_error_times in", values, "patentInfoErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesNotIn(List<Integer> values) {
            addCriterion("patent_info_error_times not in", values, "patentInfoErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesBetween(Integer value1, Integer value2) {
            addCriterion("patent_info_error_times between", value1, value2, "patentInfoErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentInfoErrorTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("patent_info_error_times not between", value1, value2, "patentInfoErrorTimes");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeIsNull() {
            addCriterion("patent_fee_wuxiao_search_type is null");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeIsNotNull() {
            addCriterion("patent_fee_wuxiao_search_type is not null");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeEqualTo(String value) {
            addCriterion("patent_fee_wuxiao_search_type =", value, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeNotEqualTo(String value) {
            addCriterion("patent_fee_wuxiao_search_type <>", value, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeGreaterThan(String value) {
            addCriterion("patent_fee_wuxiao_search_type >", value, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeGreaterThanOrEqualTo(String value) {
            addCriterion("patent_fee_wuxiao_search_type >=", value, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeLessThan(String value) {
            addCriterion("patent_fee_wuxiao_search_type <", value, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeLessThanOrEqualTo(String value) {
            addCriterion("patent_fee_wuxiao_search_type <=", value, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeLike(String value) {
            addCriterion("patent_fee_wuxiao_search_type like", value, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeNotLike(String value) {
            addCriterion("patent_fee_wuxiao_search_type not like", value, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeIn(List<String> values) {
            addCriterion("patent_fee_wuxiao_search_type in", values, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeNotIn(List<String> values) {
            addCriterion("patent_fee_wuxiao_search_type not in", values, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeBetween(String value1, String value2) {
            addCriterion("patent_fee_wuxiao_search_type between", value1, value2, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTypeNotBetween(String value1, String value2) {
            addCriterion("patent_fee_wuxiao_search_type not between", value1, value2, "patentFeeWuxiaoSearchType");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeIsNull() {
            addCriterion("patent_fee_wuxiao_search_time is null");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeIsNotNull() {
            addCriterion("patent_fee_wuxiao_search_time is not null");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeEqualTo(Date value) {
            addCriterion("patent_fee_wuxiao_search_time =", value, "patentFeeWuxiaoSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeNotEqualTo(Date value) {
            addCriterion("patent_fee_wuxiao_search_time <>", value, "patentFeeWuxiaoSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeGreaterThan(Date value) {
            addCriterion("patent_fee_wuxiao_search_time >", value, "patentFeeWuxiaoSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("patent_fee_wuxiao_search_time >=", value, "patentFeeWuxiaoSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeLessThan(Date value) {
            addCriterion("patent_fee_wuxiao_search_time <", value, "patentFeeWuxiaoSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeLessThanOrEqualTo(Date value) {
            addCriterion("patent_fee_wuxiao_search_time <=", value, "patentFeeWuxiaoSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeIn(List<Date> values) {
            addCriterion("patent_fee_wuxiao_search_time in", values, "patentFeeWuxiaoSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeNotIn(List<Date> values) {
            addCriterion("patent_fee_wuxiao_search_time not in", values, "patentFeeWuxiaoSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeBetween(Date value1, Date value2) {
            addCriterion("patent_fee_wuxiao_search_time between", value1, value2, "patentFeeWuxiaoSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentFeeWuxiaoSearchTimeNotBetween(Date value1, Date value2) {
            addCriterion("patent_fee_wuxiao_search_time not between", value1, value2, "patentFeeWuxiaoSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeIsNull() {
            addCriterion("patent_law_status_search_time is null");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeIsNotNull() {
            addCriterion("patent_law_status_search_time is not null");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeEqualTo(Date value) {
            addCriterion("patent_law_status_search_time =", value, "patentLawStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeNotEqualTo(Date value) {
            addCriterion("patent_law_status_search_time <>", value, "patentLawStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeGreaterThan(Date value) {
            addCriterion("patent_law_status_search_time >", value, "patentLawStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("patent_law_status_search_time >=", value, "patentLawStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeLessThan(Date value) {
            addCriterion("patent_law_status_search_time <", value, "patentLawStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeLessThanOrEqualTo(Date value) {
            addCriterion("patent_law_status_search_time <=", value, "patentLawStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeIn(List<Date> values) {
            addCriterion("patent_law_status_search_time in", values, "patentLawStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeNotIn(List<Date> values) {
            addCriterion("patent_law_status_search_time not in", values, "patentLawStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeBetween(Date value1, Date value2) {
            addCriterion("patent_law_status_search_time between", value1, value2, "patentLawStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentLawStatusSearchTimeNotBetween(Date value1, Date value2) {
            addCriterion("patent_law_status_search_time not between", value1, value2, "patentLawStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusIsNull() {
            addCriterion("patent_paper_status is null");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusIsNotNull() {
            addCriterion("patent_paper_status is not null");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusEqualTo(String value) {
            addCriterion("patent_paper_status =", value, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusNotEqualTo(String value) {
            addCriterion("patent_paper_status <>", value, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusGreaterThan(String value) {
            addCriterion("patent_paper_status >", value, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusGreaterThanOrEqualTo(String value) {
            addCriterion("patent_paper_status >=", value, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusLessThan(String value) {
            addCriterion("patent_paper_status <", value, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusLessThanOrEqualTo(String value) {
            addCriterion("patent_paper_status <=", value, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusLike(String value) {
            addCriterion("patent_paper_status like", value, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusNotLike(String value) {
            addCriterion("patent_paper_status not like", value, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusIn(List<String> values) {
            addCriterion("patent_paper_status in", values, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusNotIn(List<String> values) {
            addCriterion("patent_paper_status not in", values, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusBetween(String value1, String value2) {
            addCriterion("patent_paper_status between", value1, value2, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusNotBetween(String value1, String value2) {
            addCriterion("patent_paper_status not between", value1, value2, "patentPaperStatus");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeIsNull() {
            addCriterion("patent_paper_status_search_time is null");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeIsNotNull() {
            addCriterion("patent_paper_status_search_time is not null");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeEqualTo(Date value) {
            addCriterion("patent_paper_status_search_time =", value, "patentPaperStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeNotEqualTo(Date value) {
            addCriterion("patent_paper_status_search_time <>", value, "patentPaperStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeGreaterThan(Date value) {
            addCriterion("patent_paper_status_search_time >", value, "patentPaperStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("patent_paper_status_search_time >=", value, "patentPaperStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeLessThan(Date value) {
            addCriterion("patent_paper_status_search_time <", value, "patentPaperStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeLessThanOrEqualTo(Date value) {
            addCriterion("patent_paper_status_search_time <=", value, "patentPaperStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeIn(List<Date> values) {
            addCriterion("patent_paper_status_search_time in", values, "patentPaperStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeNotIn(List<Date> values) {
            addCriterion("patent_paper_status_search_time not in", values, "patentPaperStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeBetween(Date value1, Date value2) {
            addCriterion("patent_paper_status_search_time between", value1, value2, "patentPaperStatusSearchTime");
            return (Criteria) this;
        }

        public Criteria andPatentPaperStatusSearchTimeNotBetween(Date value1, Date value2) {
            addCriterion("patent_paper_status_search_time not between", value1, value2, "patentPaperStatusSearchTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.patent_main
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 01 15:58:04 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.patent_main
     *
     * @mbggenerated Sat Mar 01 15:58:04 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}