package cn.zzfyip.search.dal.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatentInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public PatentInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPatentNoIsNull() {
            addCriterion("patent_no is null");
            return (Criteria) this;
        }

        public Criteria andPatentNoIsNotNull() {
            addCriterion("patent_no is not null");
            return (Criteria) this;
        }

        public Criteria andPatentNoEqualTo(String value) {
            addCriterion("patent_no =", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoNotEqualTo(String value) {
            addCriterion("patent_no <>", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoGreaterThan(String value) {
            addCriterion("patent_no >", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoGreaterThanOrEqualTo(String value) {
            addCriterion("patent_no >=", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoLessThan(String value) {
            addCriterion("patent_no <", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoLessThanOrEqualTo(String value) {
            addCriterion("patent_no <=", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoLike(String value) {
            addCriterion("patent_no like", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoNotLike(String value) {
            addCriterion("patent_no not like", value, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoIn(List<String> values) {
            addCriterion("patent_no in", values, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoNotIn(List<String> values) {
            addCriterion("patent_no not in", values, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoBetween(String value1, String value2) {
            addCriterion("patent_no between", value1, value2, "patentNo");
            return (Criteria) this;
        }

        public Criteria andPatentNoNotBetween(String value1, String value2) {
            addCriterion("patent_no not between", value1, value2, "patentNo");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNull() {
            addCriterion("apply_date is null");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNotNull() {
            addCriterion("apply_date is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDateEqualTo(Date value) {
            addCriterion("apply_date =", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotEqualTo(Date value) {
            addCriterion("apply_date <>", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThan(Date value) {
            addCriterion("apply_date >", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("apply_date >=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThan(Date value) {
            addCriterion("apply_date <", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThanOrEqualTo(Date value) {
            addCriterion("apply_date <=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateIn(List<Date> values) {
            addCriterion("apply_date in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotIn(List<Date> values) {
            addCriterion("apply_date not in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateBetween(Date value1, Date value2) {
            addCriterion("apply_date between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotBetween(Date value1, Date value2) {
            addCriterion("apply_date not between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andPatentNameIsNull() {
            addCriterion("patent_name is null");
            return (Criteria) this;
        }

        public Criteria andPatentNameIsNotNull() {
            addCriterion("patent_name is not null");
            return (Criteria) this;
        }

        public Criteria andPatentNameEqualTo(String value) {
            addCriterion("patent_name =", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameNotEqualTo(String value) {
            addCriterion("patent_name <>", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameGreaterThan(String value) {
            addCriterion("patent_name >", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameGreaterThanOrEqualTo(String value) {
            addCriterion("patent_name >=", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameLessThan(String value) {
            addCriterion("patent_name <", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameLessThanOrEqualTo(String value) {
            addCriterion("patent_name <=", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameLike(String value) {
            addCriterion("patent_name like", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameNotLike(String value) {
            addCriterion("patent_name not like", value, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameIn(List<String> values) {
            addCriterion("patent_name in", values, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameNotIn(List<String> values) {
            addCriterion("patent_name not in", values, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameBetween(String value1, String value2) {
            addCriterion("patent_name between", value1, value2, "patentName");
            return (Criteria) this;
        }

        public Criteria andPatentNameNotBetween(String value1, String value2) {
            addCriterion("patent_name not between", value1, value2, "patentName");
            return (Criteria) this;
        }

        public Criteria andPublicNoIsNull() {
            addCriterion("public_no is null");
            return (Criteria) this;
        }

        public Criteria andPublicNoIsNotNull() {
            addCriterion("public_no is not null");
            return (Criteria) this;
        }

        public Criteria andPublicNoEqualTo(String value) {
            addCriterion("public_no =", value, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicNoNotEqualTo(String value) {
            addCriterion("public_no <>", value, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicNoGreaterThan(String value) {
            addCriterion("public_no >", value, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicNoGreaterThanOrEqualTo(String value) {
            addCriterion("public_no >=", value, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicNoLessThan(String value) {
            addCriterion("public_no <", value, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicNoLessThanOrEqualTo(String value) {
            addCriterion("public_no <=", value, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicNoLike(String value) {
            addCriterion("public_no like", value, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicNoNotLike(String value) {
            addCriterion("public_no not like", value, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicNoIn(List<String> values) {
            addCriterion("public_no in", values, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicNoNotIn(List<String> values) {
            addCriterion("public_no not in", values, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicNoBetween(String value1, String value2) {
            addCriterion("public_no between", value1, value2, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicNoNotBetween(String value1, String value2) {
            addCriterion("public_no not between", value1, value2, "publicNo");
            return (Criteria) this;
        }

        public Criteria andPublicDateIsNull() {
            addCriterion("public_date is null");
            return (Criteria) this;
        }

        public Criteria andPublicDateIsNotNull() {
            addCriterion("public_date is not null");
            return (Criteria) this;
        }

        public Criteria andPublicDateEqualTo(Date value) {
            addCriterion("public_date =", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateNotEqualTo(Date value) {
            addCriterion("public_date <>", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateGreaterThan(Date value) {
            addCriterion("public_date >", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateGreaterThanOrEqualTo(Date value) {
            addCriterion("public_date >=", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateLessThan(Date value) {
            addCriterion("public_date <", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateLessThanOrEqualTo(Date value) {
            addCriterion("public_date <=", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateIn(List<Date> values) {
            addCriterion("public_date in", values, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateNotIn(List<Date> values) {
            addCriterion("public_date not in", values, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateBetween(Date value1, Date value2) {
            addCriterion("public_date between", value1, value2, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateNotBetween(Date value1, Date value2) {
            addCriterion("public_date not between", value1, value2, "publicDate");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoIsNull() {
            addCriterion("main_category_no is null");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoIsNotNull() {
            addCriterion("main_category_no is not null");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoEqualTo(String value) {
            addCriterion("main_category_no =", value, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoNotEqualTo(String value) {
            addCriterion("main_category_no <>", value, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoGreaterThan(String value) {
            addCriterion("main_category_no >", value, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoGreaterThanOrEqualTo(String value) {
            addCriterion("main_category_no >=", value, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoLessThan(String value) {
            addCriterion("main_category_no <", value, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoLessThanOrEqualTo(String value) {
            addCriterion("main_category_no <=", value, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoLike(String value) {
            addCriterion("main_category_no like", value, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoNotLike(String value) {
            addCriterion("main_category_no not like", value, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoIn(List<String> values) {
            addCriterion("main_category_no in", values, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoNotIn(List<String> values) {
            addCriterion("main_category_no not in", values, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoBetween(String value1, String value2) {
            addCriterion("main_category_no between", value1, value2, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNoNotBetween(String value1, String value2) {
            addCriterion("main_category_no not between", value1, value2, "mainCategoryNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoIsNull() {
            addCriterion("pre_apply_no is null");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoIsNotNull() {
            addCriterion("pre_apply_no is not null");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoEqualTo(String value) {
            addCriterion("pre_apply_no =", value, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoNotEqualTo(String value) {
            addCriterion("pre_apply_no <>", value, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoGreaterThan(String value) {
            addCriterion("pre_apply_no >", value, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoGreaterThanOrEqualTo(String value) {
            addCriterion("pre_apply_no >=", value, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoLessThan(String value) {
            addCriterion("pre_apply_no <", value, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoLessThanOrEqualTo(String value) {
            addCriterion("pre_apply_no <=", value, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoLike(String value) {
            addCriterion("pre_apply_no like", value, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoNotLike(String value) {
            addCriterion("pre_apply_no not like", value, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoIn(List<String> values) {
            addCriterion("pre_apply_no in", values, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoNotIn(List<String> values) {
            addCriterion("pre_apply_no not in", values, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoBetween(String value1, String value2) {
            addCriterion("pre_apply_no between", value1, value2, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andPreApplyNoNotBetween(String value1, String value2) {
            addCriterion("pre_apply_no not between", value1, value2, "preApplyNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoIsNull() {
            addCriterion("sec_category_no is null");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoIsNotNull() {
            addCriterion("sec_category_no is not null");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoEqualTo(String value) {
            addCriterion("sec_category_no =", value, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoNotEqualTo(String value) {
            addCriterion("sec_category_no <>", value, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoGreaterThan(String value) {
            addCriterion("sec_category_no >", value, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoGreaterThanOrEqualTo(String value) {
            addCriterion("sec_category_no >=", value, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoLessThan(String value) {
            addCriterion("sec_category_no <", value, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoLessThanOrEqualTo(String value) {
            addCriterion("sec_category_no <=", value, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoLike(String value) {
            addCriterion("sec_category_no like", value, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoNotLike(String value) {
            addCriterion("sec_category_no not like", value, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoIn(List<String> values) {
            addCriterion("sec_category_no in", values, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoNotIn(List<String> values) {
            addCriterion("sec_category_no not in", values, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoBetween(String value1, String value2) {
            addCriterion("sec_category_no between", value1, value2, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andSecCategoryNoNotBetween(String value1, String value2) {
            addCriterion("sec_category_no not between", value1, value2, "secCategoryNo");
            return (Criteria) this;
        }

        public Criteria andCertificateDateIsNull() {
            addCriterion("certificate_date is null");
            return (Criteria) this;
        }

        public Criteria andCertificateDateIsNotNull() {
            addCriterion("certificate_date is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateDateEqualTo(Date value) {
            addCriterion("certificate_date =", value, "certificateDate");
            return (Criteria) this;
        }

        public Criteria andCertificateDateNotEqualTo(Date value) {
            addCriterion("certificate_date <>", value, "certificateDate");
            return (Criteria) this;
        }

        public Criteria andCertificateDateGreaterThan(Date value) {
            addCriterion("certificate_date >", value, "certificateDate");
            return (Criteria) this;
        }

        public Criteria andCertificateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("certificate_date >=", value, "certificateDate");
            return (Criteria) this;
        }

        public Criteria andCertificateDateLessThan(Date value) {
            addCriterion("certificate_date <", value, "certificateDate");
            return (Criteria) this;
        }

        public Criteria andCertificateDateLessThanOrEqualTo(Date value) {
            addCriterion("certificate_date <=", value, "certificateDate");
            return (Criteria) this;
        }

        public Criteria andCertificateDateIn(List<Date> values) {
            addCriterion("certificate_date in", values, "certificateDate");
            return (Criteria) this;
        }

        public Criteria andCertificateDateNotIn(List<Date> values) {
            addCriterion("certificate_date not in", values, "certificateDate");
            return (Criteria) this;
        }

        public Criteria andCertificateDateBetween(Date value1, Date value2) {
            addCriterion("certificate_date between", value1, value2, "certificateDate");
            return (Criteria) this;
        }

        public Criteria andCertificateDateNotBetween(Date value1, Date value2) {
            addCriterion("certificate_date not between", value1, value2, "certificateDate");
            return (Criteria) this;
        }

        public Criteria andPreRightIsNull() {
            addCriterion("pre_right is null");
            return (Criteria) this;
        }

        public Criteria andPreRightIsNotNull() {
            addCriterion("pre_right is not null");
            return (Criteria) this;
        }

        public Criteria andPreRightEqualTo(String value) {
            addCriterion("pre_right =", value, "preRight");
            return (Criteria) this;
        }

        public Criteria andPreRightNotEqualTo(String value) {
            addCriterion("pre_right <>", value, "preRight");
            return (Criteria) this;
        }

        public Criteria andPreRightGreaterThan(String value) {
            addCriterion("pre_right >", value, "preRight");
            return (Criteria) this;
        }

        public Criteria andPreRightGreaterThanOrEqualTo(String value) {
            addCriterion("pre_right >=", value, "preRight");
            return (Criteria) this;
        }

        public Criteria andPreRightLessThan(String value) {
            addCriterion("pre_right <", value, "preRight");
            return (Criteria) this;
        }

        public Criteria andPreRightLessThanOrEqualTo(String value) {
            addCriterion("pre_right <=", value, "preRight");
            return (Criteria) this;
        }

        public Criteria andPreRightLike(String value) {
            addCriterion("pre_right like", value, "preRight");
            return (Criteria) this;
        }

        public Criteria andPreRightNotLike(String value) {
            addCriterion("pre_right not like", value, "preRight");
            return (Criteria) this;
        }

        public Criteria andPreRightIn(List<String> values) {
            addCriterion("pre_right in", values, "preRight");
            return (Criteria) this;
        }

        public Criteria andPreRightNotIn(List<String> values) {
            addCriterion("pre_right not in", values, "preRight");
            return (Criteria) this;
        }

        public Criteria andPreRightBetween(String value1, String value2) {
            addCriterion("pre_right between", value1, value2, "preRight");
            return (Criteria) this;
        }

        public Criteria andPreRightNotBetween(String value1, String value2) {
            addCriterion("pre_right not between", value1, value2, "preRight");
            return (Criteria) this;
        }

        public Criteria andApplierIsNull() {
            addCriterion("applier is null");
            return (Criteria) this;
        }

        public Criteria andApplierIsNotNull() {
            addCriterion("applier is not null");
            return (Criteria) this;
        }

        public Criteria andApplierEqualTo(String value) {
            addCriterion("applier =", value, "applier");
            return (Criteria) this;
        }

        public Criteria andApplierNotEqualTo(String value) {
            addCriterion("applier <>", value, "applier");
            return (Criteria) this;
        }

        public Criteria andApplierGreaterThan(String value) {
            addCriterion("applier >", value, "applier");
            return (Criteria) this;
        }

        public Criteria andApplierGreaterThanOrEqualTo(String value) {
            addCriterion("applier >=", value, "applier");
            return (Criteria) this;
        }

        public Criteria andApplierLessThan(String value) {
            addCriterion("applier <", value, "applier");
            return (Criteria) this;
        }

        public Criteria andApplierLessThanOrEqualTo(String value) {
            addCriterion("applier <=", value, "applier");
            return (Criteria) this;
        }

        public Criteria andApplierLike(String value) {
            addCriterion("applier like", value, "applier");
            return (Criteria) this;
        }

        public Criteria andApplierNotLike(String value) {
            addCriterion("applier not like", value, "applier");
            return (Criteria) this;
        }

        public Criteria andApplierIn(List<String> values) {
            addCriterion("applier in", values, "applier");
            return (Criteria) this;
        }

        public Criteria andApplierNotIn(List<String> values) {
            addCriterion("applier not in", values, "applier");
            return (Criteria) this;
        }

        public Criteria andApplierBetween(String value1, String value2) {
            addCriterion("applier between", value1, value2, "applier");
            return (Criteria) this;
        }

        public Criteria andApplierNotBetween(String value1, String value2) {
            addCriterion("applier not between", value1, value2, "applier");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andInventorIsNull() {
            addCriterion("inventor is null");
            return (Criteria) this;
        }

        public Criteria andInventorIsNotNull() {
            addCriterion("inventor is not null");
            return (Criteria) this;
        }

        public Criteria andInventorEqualTo(String value) {
            addCriterion("inventor =", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorNotEqualTo(String value) {
            addCriterion("inventor <>", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorGreaterThan(String value) {
            addCriterion("inventor >", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorGreaterThanOrEqualTo(String value) {
            addCriterion("inventor >=", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorLessThan(String value) {
            addCriterion("inventor <", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorLessThanOrEqualTo(String value) {
            addCriterion("inventor <=", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorLike(String value) {
            addCriterion("inventor like", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorNotLike(String value) {
            addCriterion("inventor not like", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorIn(List<String> values) {
            addCriterion("inventor in", values, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorNotIn(List<String> values) {
            addCriterion("inventor not in", values, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorBetween(String value1, String value2) {
            addCriterion("inventor between", value1, value2, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorNotBetween(String value1, String value2) {
            addCriterion("inventor not between", value1, value2, "inventor");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentIsNull() {
            addCriterion("global_patent is null");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentIsNotNull() {
            addCriterion("global_patent is not null");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentEqualTo(String value) {
            addCriterion("global_patent =", value, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentNotEqualTo(String value) {
            addCriterion("global_patent <>", value, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentGreaterThan(String value) {
            addCriterion("global_patent >", value, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentGreaterThanOrEqualTo(String value) {
            addCriterion("global_patent >=", value, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentLessThan(String value) {
            addCriterion("global_patent <", value, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentLessThanOrEqualTo(String value) {
            addCriterion("global_patent <=", value, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentLike(String value) {
            addCriterion("global_patent like", value, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentNotLike(String value) {
            addCriterion("global_patent not like", value, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentIn(List<String> values) {
            addCriterion("global_patent in", values, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentNotIn(List<String> values) {
            addCriterion("global_patent not in", values, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentBetween(String value1, String value2) {
            addCriterion("global_patent between", value1, value2, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPatentNotBetween(String value1, String value2) {
            addCriterion("global_patent not between", value1, value2, "globalPatent");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicIsNull() {
            addCriterion("global_public is null");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicIsNotNull() {
            addCriterion("global_public is not null");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicEqualTo(String value) {
            addCriterion("global_public =", value, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicNotEqualTo(String value) {
            addCriterion("global_public <>", value, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicGreaterThan(String value) {
            addCriterion("global_public >", value, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicGreaterThanOrEqualTo(String value) {
            addCriterion("global_public >=", value, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicLessThan(String value) {
            addCriterion("global_public <", value, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicLessThanOrEqualTo(String value) {
            addCriterion("global_public <=", value, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicLike(String value) {
            addCriterion("global_public like", value, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicNotLike(String value) {
            addCriterion("global_public not like", value, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicIn(List<String> values) {
            addCriterion("global_public in", values, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicNotIn(List<String> values) {
            addCriterion("global_public not in", values, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicBetween(String value1, String value2) {
            addCriterion("global_public between", value1, value2, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andGlobalPublicNotBetween(String value1, String value2) {
            addCriterion("global_public not between", value1, value2, "globalPublic");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateIsNull() {
            addCriterion("entry_country_date is null");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateIsNotNull() {
            addCriterion("entry_country_date is not null");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateEqualTo(Date value) {
            addCriterion("entry_country_date =", value, "entryCountryDate");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateNotEqualTo(Date value) {
            addCriterion("entry_country_date <>", value, "entryCountryDate");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateGreaterThan(Date value) {
            addCriterion("entry_country_date >", value, "entryCountryDate");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateGreaterThanOrEqualTo(Date value) {
            addCriterion("entry_country_date >=", value, "entryCountryDate");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateLessThan(Date value) {
            addCriterion("entry_country_date <", value, "entryCountryDate");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateLessThanOrEqualTo(Date value) {
            addCriterion("entry_country_date <=", value, "entryCountryDate");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateIn(List<Date> values) {
            addCriterion("entry_country_date in", values, "entryCountryDate");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateNotIn(List<Date> values) {
            addCriterion("entry_country_date not in", values, "entryCountryDate");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateBetween(Date value1, Date value2) {
            addCriterion("entry_country_date between", value1, value2, "entryCountryDate");
            return (Criteria) this;
        }

        public Criteria andEntryCountryDateNotBetween(Date value1, Date value2) {
            addCriterion("entry_country_date not between", value1, value2, "entryCountryDate");
            return (Criteria) this;
        }

        public Criteria andAgencyIsNull() {
            addCriterion("agency is null");
            return (Criteria) this;
        }

        public Criteria andAgencyIsNotNull() {
            addCriterion("agency is not null");
            return (Criteria) this;
        }

        public Criteria andAgencyEqualTo(String value) {
            addCriterion("agency =", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotEqualTo(String value) {
            addCriterion("agency <>", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyGreaterThan(String value) {
            addCriterion("agency >", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyGreaterThanOrEqualTo(String value) {
            addCriterion("agency >=", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyLessThan(String value) {
            addCriterion("agency <", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyLessThanOrEqualTo(String value) {
            addCriterion("agency <=", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyLike(String value) {
            addCriterion("agency like", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotLike(String value) {
            addCriterion("agency not like", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyIn(List<String> values) {
            addCriterion("agency in", values, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotIn(List<String> values) {
            addCriterion("agency not in", values, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyBetween(String value1, String value2) {
            addCriterion("agency between", value1, value2, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotBetween(String value1, String value2) {
            addCriterion("agency not between", value1, value2, "agency");
            return (Criteria) this;
        }

        public Criteria andAgentIsNull() {
            addCriterion("agent is null");
            return (Criteria) this;
        }

        public Criteria andAgentIsNotNull() {
            addCriterion("agent is not null");
            return (Criteria) this;
        }

        public Criteria andAgentEqualTo(String value) {
            addCriterion("agent =", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotEqualTo(String value) {
            addCriterion("agent <>", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentGreaterThan(String value) {
            addCriterion("agent >", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentGreaterThanOrEqualTo(String value) {
            addCriterion("agent >=", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLessThan(String value) {
            addCriterion("agent <", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLessThanOrEqualTo(String value) {
            addCriterion("agent <=", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLike(String value) {
            addCriterion("agent like", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotLike(String value) {
            addCriterion("agent not like", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentIn(List<String> values) {
            addCriterion("agent in", values, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotIn(List<String> values) {
            addCriterion("agent not in", values, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentBetween(String value1, String value2) {
            addCriterion("agent between", value1, value2, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotBetween(String value1, String value2) {
            addCriterion("agent not between", value1, value2, "agent");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("summary is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("summary is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("summary =", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("summary <>", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("summary >", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("summary >=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("summary <", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("summary <=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("summary like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("summary not like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryIn(List<String> values) {
            addCriterion("summary in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotIn(List<String> values) {
            addCriterion("summary not in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("summary between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("summary not between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNull() {
            addCriterion("add_date is null");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNotNull() {
            addCriterion("add_date is not null");
            return (Criteria) this;
        }

        public Criteria andAddDateEqualTo(Date value) {
            addCriterion("add_date =", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotEqualTo(Date value) {
            addCriterion("add_date <>", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThan(Date value) {
            addCriterion("add_date >", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThanOrEqualTo(Date value) {
            addCriterion("add_date >=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThan(Date value) {
            addCriterion("add_date <", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThanOrEqualTo(Date value) {
            addCriterion("add_date <=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateIn(List<Date> values) {
            addCriterion("add_date in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotIn(List<Date> values) {
            addCriterion("add_date not in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateBetween(Date value1, Date value2) {
            addCriterion("add_date between", value1, value2, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotBetween(Date value1, Date value2) {
            addCriterion("add_date not between", value1, value2, "addDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.patent_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 27 00:22:43 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.patent_info
     *
     * @mbggenerated Fri Dec 27 00:22:43 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}