package cn.zzfyip.search.dal.common.entity;

import java.util.Date;

public class PatentNoticeFawen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_notice_fawen.id
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_notice_fawen.patent_no
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    private String patentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_notice_fawen.notice_date
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    private Date noticeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_notice_fawen.register_no
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    private String registerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_notice_fawen.notice_code
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    private String noticeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_notice_fawen.receiver
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_notice_fawen.address
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_notice_fawen.add_date
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    private Date addDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.patent_notice_fawen.sequnce_no
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    private Integer sequnceNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_notice_fawen.id
     *
     * @return the value of public.patent_notice_fawen.id
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_notice_fawen.id
     *
     * @param id the value for public.patent_notice_fawen.id
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_notice_fawen.patent_no
     *
     * @return the value of public.patent_notice_fawen.patent_no
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public String getPatentNo() {
        return patentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_notice_fawen.patent_no
     *
     * @param patentNo the value for public.patent_notice_fawen.patent_no
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public void setPatentNo(String patentNo) {
        this.patentNo = patentNo == null ? null : patentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_notice_fawen.notice_date
     *
     * @return the value of public.patent_notice_fawen.notice_date
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public Date getNoticeDate() {
        return noticeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_notice_fawen.notice_date
     *
     * @param noticeDate the value for public.patent_notice_fawen.notice_date
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public void setNoticeDate(Date noticeDate) {
        this.noticeDate = noticeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_notice_fawen.register_no
     *
     * @return the value of public.patent_notice_fawen.register_no
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public String getRegisterNo() {
        return registerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_notice_fawen.register_no
     *
     * @param registerNo the value for public.patent_notice_fawen.register_no
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public void setRegisterNo(String registerNo) {
        this.registerNo = registerNo == null ? null : registerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_notice_fawen.notice_code
     *
     * @return the value of public.patent_notice_fawen.notice_code
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public String getNoticeCode() {
        return noticeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_notice_fawen.notice_code
     *
     * @param noticeCode the value for public.patent_notice_fawen.notice_code
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public void setNoticeCode(String noticeCode) {
        this.noticeCode = noticeCode == null ? null : noticeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_notice_fawen.receiver
     *
     * @return the value of public.patent_notice_fawen.receiver
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_notice_fawen.receiver
     *
     * @param receiver the value for public.patent_notice_fawen.receiver
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_notice_fawen.address
     *
     * @return the value of public.patent_notice_fawen.address
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_notice_fawen.address
     *
     * @param address the value for public.patent_notice_fawen.address
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_notice_fawen.add_date
     *
     * @return the value of public.patent_notice_fawen.add_date
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_notice_fawen.add_date
     *
     * @param addDate the value for public.patent_notice_fawen.add_date
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.patent_notice_fawen.sequnce_no
     *
     * @return the value of public.patent_notice_fawen.sequnce_no
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public Integer getSequnceNo() {
        return sequnceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.patent_notice_fawen.sequnce_no
     *
     * @param sequnceNo the value for public.patent_notice_fawen.sequnce_no
     *
     * @mbggenerated Thu Jan 09 21:11:26 CST 2014
     */
    public void setSequnceNo(Integer sequnceNo) {
        this.sequnceNo = sequnceNo;
    }
}